build_gameserver:
  stage: build
  image: moby/buildkit:v0.28.1-rootless

  script:
    - |
      buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context=. \
        --local dockerfile=. \
        --opt filename=./docker/gameserver.Dockerfile \
        --output type=image,name=$CI_REGISTRY_IMAGE/gameserver:$CI_COMMIT_REF_SLUG,push=true
